---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - jobs
  - persistentvolumeclaims
  - pods
  - pods/status
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlbackups
  - mysqlbackups/finalizers
  - mysqlbackups/status
  - mysqlclusters
  - mysqlclusters/finalizers
  - mysqlclusters/status
  - mysqldatabases
  - mysqldatabases/finalizers
  - mysqldatabases/status
  - mysqlrestores
  - mysqlusers
  - mysqlusers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlrestores/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
